require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PhonesController do

  def mock_phone(stubs={})
    @mock_phone ||= mock_model(Phone, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all phones as @phones" do
      Phone.stub(:all) { [mock_phone] }
      get :index
      assigns(:phones).should eq([mock_phone])
    end
  end

  describe "GET show" do
    it "assigns the requested phone as @phone" do
      Phone.stub(:find).with("37") { mock_phone }
      get :show, :id => "37"
      assigns(:phone).should be(mock_phone)
    end
  end

  describe "GET new" do
    it "assigns a new phone as @phone" do
      Phone.stub(:new) { mock_phone }
      get :new
      assigns(:phone).should be(mock_phone)
    end
  end

  describe "GET edit" do
    it "assigns the requested phone as @phone" do
      Phone.stub(:find).with("37") { mock_phone }
      get :edit, :id => "37"
      assigns(:phone).should be(mock_phone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created phone as @phone" do
        Phone.stub(:new).with({'these' => 'params'}) { mock_phone(:save => true) }
        post :create, :phone => {'these' => 'params'}
        assigns(:phone).should be(mock_phone)
      end

      it "redirects to the created phone" do
        Phone.stub(:new) { mock_phone(:save => true) }
        post :create, :phone => {}
        response.should redirect_to(phone_url(mock_phone))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phone as @phone" do
        Phone.stub(:new).with({'these' => 'params'}) { mock_phone(:save => false) }
        post :create, :phone => {'these' => 'params'}
        assigns(:phone).should be(mock_phone)
      end

      it "re-renders the 'new' template" do
        Phone.stub(:new) { mock_phone(:save => false) }
        post :create, :phone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phone" do
        Phone.stub(:find).with("37") { mock_phone }
        mock_phone.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :phone => {'these' => 'params'}
      end

      it "assigns the requested phone as @phone" do
        Phone.stub(:find) { mock_phone(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:phone).should be(mock_phone)
      end

      it "redirects to the phone" do
        Phone.stub(:find) { mock_phone(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(phone_url(mock_phone))
      end
    end

    describe "with invalid params" do
      it "assigns the phone as @phone" do
        Phone.stub(:find) { mock_phone(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:phone).should be(mock_phone)
      end

      it "re-renders the 'edit' template" do
        Phone.stub(:find) { mock_phone(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phone" do
      Phone.stub(:find).with("37") { mock_phone }
      mock_phone.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the phones list" do
      Phone.stub(:find) { mock_phone }
      delete :destroy, :id => "1"
      response.should redirect_to(phones_url)
    end
  end

end
